### ISSUE TITLE
Video direction influenced by setTargetVideoSize

### ISSUE THREAD

**Issue by ItsRay** [lakeinchina/librestreaming#125]
Hi,
I want to ask the usage of [setTargetVideoSize](https://github.com/lakeinchina/librestreaming/blob/master/sample/src/main/java/me/lake/librestreaming/sample/BaseStreamingActivity.java#L86) in sample.
If I put argument 720x480, the target video will be portrait screen.
If I put argument 480x480, the target video will be landscape screen.
Is this result in your expectation?

If it's not in expectation, maybe changing [these two lines](https://github.com/lakeinchina/librestreaming/blob/master/librestreaming/src/main/java/me/lake/librestreaming/client/RESVideoClient.java#L433) could reverse it.

sincerely

**Comment by developeralp** [comment]
Hello,

I think you should choose 720x480 for portrait stream and 480x720 for landscape stream

if you choose 480x480 , stream will be square ; not portrait or landscape.

**Comment by lakeinchina** [comment]
The api of android camera can only set landscape size and output landscape image. So, at the very beginning，I hope the setTargetVideoSize set camera output size directly , so it should set a landscape size.but in order to get portrait size I add setFrontCameraDirectionMode&setBackCameraDirectionMode which control the direction.so all you need to do is set a landscape size and rotate it by set***CameraDirectionMode.
It was confusing. in the  sample code ,set***CameraDirectionMode is complex, mainly because of camera output image`s direction is a mess. I should have dealt with this problem inside the lib.

In general, if you set 720\*480 and set FLAG_DIRECTION_ROATATION_270 or FLAG_DIRECTION_ROATATION_90, you will get a 480\*720 stream.if you set FLAG_DIRECTION_ROATATION_0 or FLAG_DIRECTION_ROATATION_180,you will get a 720\*480 stream.
the sample code works good in most case, it rotate video in the right direction, all you have to do is modify setTargetVideoSize with a landscape size.
you certainly can set a 480\*720 with FLAG_DIRECTION_ROATATION_90 and get a 720\*480 stream but The image was cropped.i don\`t suggest you to do that.

**Comment by ItsRay** [comment]
Thank you for your explanation.
