### ISSUE TITLE
Sound/Image out of sync

### ISSUE THREAD

**Issue by psegalen** [lakeinchina/librestreaming#205]
Hi @lakeinchina, thank you very much for this SDK!
On some devices it seems the sound is out of sync with the image (720p @ 2.5 Mbps), sound is about 500ms ahead of image.
Do you have any lead on how to address this issue?

**Comment by lakeinchina** [comment]
sorry,I am no longer working on this project.
but this problem should be caused by presentationTimeUs in AudioSenderThread&VideoSenderThread，and this variable comes from nowTimeMs&drawMediaCodec() in RESSoftAudioCore&RESHardVideoCore.

Audio timestamp of this project is a bad design，maybe you should focus on it.

**Comment by psegalen** [comment]
Thank you for your answer and your insight about the problem, from what I could gather it seems that Camera1 API isn't suitable for what I need to achieve, I'll find another lib based on Camera2.
